language: python
python:
  - '2.7'
install: "pip install -r requirements.txt"
script: 
  - pytest --cov-report term-missing --cov=./app
after_success:
  - coveralls
cache: pip
after_success:
    - coveralls
    - codecov --token=77d3a35c-2483-44d9-b4be-fdb97a75b66b
    - pylint --output-format=html pylint_server > /tmp/pylint-report.html
    - curl -v -m 120 -X POST -F travis-job-id=$TRAVIS_JOB_ID -F pylint-report=@/tmp/pylint-report.html https://pylint.yourserver.com/reports
