language: python
python:
  - '3.6'
  
install: 
  - pip install -r requirements.txt
  - pip install coveralls codecov

script: 
  - pytest --cov-report term-missing --cov=./app
  
after_success:
    - coveralls
    - codecov --token=77d3a35c-2483-44d9-b4be-fdb97a75b66b
